version: '3'
services:
  php_app:
    build: './etender_app'
    networks:
    - app_net
    volumes:
    - ./etender_app/etender-dev:/var/www/html
    - ./etender_app/php.ini:/usr/local/etc/php/php.ini
    - /home/steffan/logs:/var/logs

  apache_server:
    build: './apache_server'
    depends_on:
    - php_app
    networks:
    - app_net
    ports:
    - "8080:80"
    volumes:
    - ./etender_app/etender-dev:/var/www/html

networks:
  app_net: