version: '3'
services:
  php_app:
    build: './php_fpm_app'
    volumes:
    - ./php_fpm_app/cm-test-repo:/var/www/html
    networks:
    - app_net

  apache_server:
    build: './apache_server'
    depends_on:
    - php_app
    networks:
    - app_net
    ports:
    - "8080:80"
    volumes:
    - ./php_fpm_app/cm-test-repo:/var/www/html

networks:
  app_net: