version: '3'
services:
  php_app:
    build: './etender'
    networks:
    - app_net
    volumes:
    - ./etender/app:/var/www/html/etender

  apache_server:
    build: './apache_server'
    depends_on:
    - php_app
    networks:
    - app_net
    ports:
    - "8080:80"
    volumes:
    - ./etender/app:/var/www/html/etender

networks:
  app_net: